FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# todolistdss

Todo is an API allowing users to create todos, delete them, and mark them as complete.

-todos
    -title
    -created_at
    -updated_at
    -completed
    -order