FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# todolistdss

# Group Todos

Todos operations.

## Creation of todo

+ Attributes (object)

  + title - Todo Title
  + completed - Boolean if the todo is completed
  + order - The todos order in the list

### Add a car [POST]

+ Request Creating a car (application/json)

    + Headers

            Accept: application/json

    + Body

            {
              "todo": {
                "title": "First Todo",
                "completed": false,
                "order": 0
              }
            }

+ Response 201 (application/json)

    + Headers

    + Body

            {
                "id": 1,
                "title": "First Todo",
                "completed": false,
                "order": 0
            }

+ Request Fails when missing params (application/json)

    + Headers

            Accept: application/json

    + Body

            {
              "todo": {
                "title": "First Todo",
                "completed": false,
                "order": 0
              }
            }

+ Response 400 (application/json)

    + Headers

    + Body

            {
              "brand": [
                "can't be blank"
              ]
            }

## Single Todo [/{id}]

+ Parameters

  + id: 1 (required, string) - Car id

### Deletes a specific car [DELETE]

+ Request Deleting a car (application/json)

    + Headers

            Accept: application/json

+ Response 204 ()